# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-30 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_entradas_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradas_estoque',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estoque.Categoria', verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estoque.Categoria', verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(max_length=300, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque',
            field=models.IntegerField(default=0, verbose_name='Estoque atual'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque_min',
            field=models.PositiveIntegerField(default=0, verbose_name='Estoque mínimo'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='importado',
            field=models.BooleanField(default=False, verbose_name='Importado'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='ipi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, verbose_name='IPI'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_compra',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Preço De Compra'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_venda',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Preço De Venda'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='produto',
            field=models.CharField(max_length=100, unique=True, verbose_name='Produto'),
        ),
    ]
