# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-10 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordem_Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lista_produtos', models.CharField(max_length=50)),
                ('tipo_servivo', models.CharField(max_length=50)),
                ('data_entrega', models.DateField()),
                ('status_servico', models.CharField(choices=[(b'P', b'Pendente'), (b'C', b'Concluido')], max_length=2)),
                ('observacao', models.TextField()),
                ('data_emissao', models.DateField()),
                ('clientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('preco', models.CharField(max_length=5)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
