# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-30 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem_servico',
            name='clientes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='ordem_servico',
            name='data_emissao',
            field=models.DateField(verbose_name='Data De Emissão'),
        ),
        migrations.AlterField(
            model_name='ordem_servico',
            name='data_entrega',
            field=models.DateField(verbose_name='Data de entrega'),
        ),
        migrations.AlterField(
            model_name='ordem_servico',
            name='lista_produtos',
            field=models.CharField(max_length=50, verbose_name='Produto Deixado'),
        ),
        migrations.AlterField(
            model_name='ordem_servico',
            name='observacao',
            field=models.TextField(verbose_name='Relatório'),
        ),
        migrations.AlterField(
            model_name='ordem_servico',
            name='status_servico',
            field=models.CharField(choices=[('P', 'Pendente'), ('C', 'Concluido')], default='P', max_length=2, verbose_name='Status Do Serviço'),
        ),
        migrations.AlterField(
            model_name='ordem_servico',
            name='tipo_servivo',
            field=models.CharField(max_length=50, verbose_name='Tipo Do Serviço'),
        ),
    ]
