# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-31 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_auto_20180130_1844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordem_servico',
            options={'verbose_name': 'Ordem de Serviço', 'verbose_name_plural': 'Ordem de Serviços'},
        ),
        migrations.AddField(
            model_name='ordem_servico',
            name='numero_os',
            field=models.CharField(default=1, max_length=6, unique=True, verbose_name='Numero da Os'),
            preserve_default=False,
        ),
    ]
