# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-07 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=35, verbose_name=b'Nome')),
                ('cpf', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name=b'CPF')),
                ('sexo', models.CharField(blank=True, choices=[(b'F', b'Feminino'), (b'M', b'Masculino')], max_length=1, verbose_name=b'Sexo')),
                ('nascimento', models.DateField(verbose_name=b'Data De Nascimento')),
                ('email', models.EmailField(blank=True, max_length=30, verbose_name=b'E-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name=b'Telefone')),
                ('instagran', models.CharField(blank=True, max_length=20, verbose_name=b'Instagran')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
