# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-30 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=30, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='instagran',
            field=models.CharField(blank=True, max_length=20, verbose_name='Instagran'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nascimento',
            field=models.DateField(verbose_name='Data De Nascimento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=35, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(blank=True, choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone'),
        ),
    ]
